### ISSUE TITLE
Support OpenVPN

### ISSUE THREAD

**Issue by kaffeeringe** [ozonos/ozon-packaging#3]
Hi! I am not sure if this is the right issues tracker.

I times of mass surveillance it would be nice to make encryption as easy as possible. I installed OpenVPN on my Raspberry Pi and found out that it's not too easy to set up the client side. 

It seems that there's only PPTP in place at the moment.

I had to install openvpn and NetworkManager-openvpn-gnome. And then I had to manually set up all the certificates and the config. It would be cool if OzonOS supported the import of .ovpn files - like the "OpenVPN Connect" app for Android devices.

**Comment by kaffeeringe** [comment]
I documented my steps here: https://kaffeeringe.de/3983/openvpn-client-unter-ozonos-einrichten/ (German)

There's one problem left: I have to restart openvpn ever time the systems wakes up from suspend mode. Of course it loses connection, when the notebook is off. It would be best if the system stops openvpn pre suspend and starts it up again on wake up.

**Comment by Foggalong** [comment]
[Issue tracker is here](https://github.com/ozonos/bug-tracker-BETA)
